version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: todo-mongo
    volumes:
      - mongo-data:/data/db
    restart: always

  api:
    build: ./api
    container_name: todo-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
    restart: unless-stopped

volumes:
  mongo-data: